name: Generate Image List JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create image list JSON
      run: |
        # Создаем папку Images, если ее нет
        mkdir -p Images
        # Начинаем формирование JSON файла (перезаписываем его заново)
        echo "[" > image_list.json
        # Перебираем все изображения в папке Images, поддерживая пробелы в именах файлов
        count=0
        while IFS= read -r -d '' file; do
          echo "{\"name\": \"$(basename "$file")\", \"path\": \"$file\"}," >> image_list.json
          count=$((count+1))
        done < <(find Images/ -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -print0)

        # Проверяем, есть ли добавленные изображения
        if [ "$count" -gt 0 ]; then
          # Убираем последнюю запятую и закрываем JSON массив
          sed -i '$ s/,$//' image_list.json
        fi
        echo "]" >> image_list.json

    - name: Commit and push image list JSON
      env:
         ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config --global user.email "govnoed830@gmail.com"
        git config --global user.name "v0rvex"
        git add image_list.json
        git commit -m "Update image_list.json"
        git push

    - uses: stefanzweifel/git-auto-commit-action@v5
